version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - dba_data:/var/lib/mysql
    restart: always
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: iheb123
      MYSQL_DATABASE: test_db
      MYSQL_PASSWORD: iheb123


  # phpmyadmin
  phpmyadmin_new:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: iheb123


volumes:
  dba_data:
